Задача 1

Даны значения величины заработной платы заемщиков банка (salary) и значения их поведенческого кредитного скоринга (scoring):

salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]
Используя только встроенные питоновские функции и структуры данных (т.е. без библиотек numpy, pandas и др.) найдите:

ковариацию (смещённую и несмещённую) этих двух величин,
коэффициент корреляции Пирсона.
Можно затем посчитать те же значения с использованием библиотек, чтобы проверить себя.

In [1]:
# Найдем все  только с использованием встроенных функций python

salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]

def cov(arr1, arr2):
    ind, result, sum1, sum2 = 0, 0, 0, 0
    for i in arr1:
        sum1 += i
        mean1 = sum1/len(arr1)
    for m in arr2:
        sum2 += i
        mean2 = sum2/len(arr2)
    while ind != len(arr1):
        m = (arr1[ind]-mean1)*(arr2[ind]-mean2)
        result += m
        ind += 1
    return result/(len(arr1)-1)

print(cov(salary, scoring))
def std(arr):
    sum, result = 0, 0
    for i in arr:
        sum += i
        mean = sum/(len(arr))
    for i in arr:
        disp = ((i-mean)**2)
        result += disp/(len(arr)-1)
    return result**0.5

    
def pearson(cov):
    return cov/(std(salary)*std(scoring))

print(pearson(cov(salary, scoring)))

10175.377777777774
0.887490092073916


In [2]:
# С частичным использованием numpy
import numpy as np
import pandas as pd


print('Принты только для праверки правильности функции стандартного отклонения')
print(std(salary), np.std(salary, ddof = 1))
print(std(scoring), np.std(scoring, ddof = 1))





Принты только для праверки правильности функции стандартного отклонения
62.31318747531163 62.31318747531162
183.99544076477062 183.99544076477068


In [3]:
# С частичным использованием numpy

print(np.std(scoring, ddof = 1))
n = len(salary)
sigma_salary_scoring = ((salary - np.mean(salary))*(scoring-np.mean(scoring))).sum()/(n-1) # Ковариация
cov = sigma_salary_scoring/(np.std(salary, ddof = 1)*np.std(scoring, ddof = 1)) # коэффициент корреляции Пирсона.
sigma_salary_scoring, cov

183.99544076477068


(10175.37777777778, 0.8874900920739164)

In [4]:
np.cov(salary, scoring, ddof = 0) # смещенная

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [5]:
np.cov(salary, scoring, ddof = 1) # несмещенная. Проверяем - совпадает

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [6]:
np.corrcoef(salary,scoring) # Проверяем - совпадает

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

### Задача 2

Проведите тест на значимость коэффициента корреляции Пирсона, найденного в предыдущей задаче. Что для этого нужно знать:

Нулевая гипотеза: реальный коэффициент корреляции равен 0. Альтернативная гипотеза двухсторонняя.
Статистика: t = r * sqrt(n - 2) / sqrt(1 - r ** 2), где r - коэффициент корреляции Пирсона, посчитанный по выборке.
В предположении верности нулевой гипотезы эта статистика имеет распределение Стьюдента с параметром df = n - 2.

In [7]:
from scipy import stats
alpha = 0.05
tl = stats.t.ppf(alpha/2, df = n - 2)
tr = stats.t.ppf(1-alpha/2, df = n - 2)
tl, tr

(-2.306004135033371, 2.3060041350333704)

In [8]:
r = cov
t0 = r*np.sqrt(n-2)/np.sqrt(1-r**2)
t0

5.447168150485581

In [9]:
vr = 1-stats.t.cdf(t0, df = n-2)
vl = stats.t.cdf(t0, df = n-2)

print(2*min(vr, vl))

0.0006107546587257318


Вывод: Нулевая гипотеза отвергается, так как результат находится в критической области и значение p-value < 0.05

### Задача 3

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111
Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [10]:
import numpy as np
from scipy import stats

In [11]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = len(iq)

In [12]:
alpha = 0.05

In [13]:
tl = stats.t.ppf(alpha/2, df = n-1)
tr = stats.t.ppf(1-alpha/2, df = n-1)

In [14]:
tl, tr

(-2.262157162740992, 2.2621571627409915)

In [15]:
f'Доверительный интервал: {np.mean(iq) + tl*np.std(iq)/np.sqrt(n), np.mean(iq) + tr*np.std(iq)/np.sqrt(n)}'

'Доверительный интервал: (110.9432125583706, 125.25678744162938)'

### Задача 4

Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики и напишите ее в комментарии к Практическому заданию.

Планирую взять данный датасет - https://www.kaggle.com/ronitf/heart-disease-uci

In [18]:
source = 'data/heart.csv'
df = pd.read_csv(source)
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
5     57    1   0       140   192    0        1      148      0      0.4   
6     56    0   1       140   294    0        0      153      0      1.3   
7     44    1   1       120   263    0        1      173      0      0.0   
8     52    1   2       172   199    1        1      162      0      0.5   
9     57    1   2       150   168    0        1      174      0      1.6   
10    54    1   0       140   239    0        1      160      0      1.2   
11    48    0   2       130   275    0        1      139      0      0.2   
12    49    1   1       130   266    0        1      171      0      0.6   
13    64    1   3       110   211    0        0      144      1      1.8   
14    58    0   3       150   283    1        0      162      0      1.0   
15    50    0   2       120   219    0        1      158      0      1.6   
16    58    0   2       120   340    0        1      172      0      0.0   
17    66    0   3       150   226    0        1      114      0      2.6   
18    43    1   0       150   247    0        1      171      0      1.5   
19    69    0   3       140   239    0        1      151      0      1.8   
20    59    1   0       135   234    0        1      161      0      0.5   
21    44    1   2       130   233    0        1      179      1      0.4   
22    42    1   0       140   226    0        1      178      0      0.0   
23    61    1   2       150   243    1        1      137      1      1.0   
24    40    1   3       140   199    0        1      178      1      1.4   
25    71    0   1       160   302    0        1      162      0      0.4   
26    59    1   2       150   212    1        1      157      0      1.6   
27    51    1   2       110   175    0        1      123      0      0.6   
28    65    0   2       140   417    1        0      157      0      0.8   
29    53    1   2       130   197    1        0      152      0      1.2   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
273   58    1   0       100   234    0        1      156      0      0.1   
274   47    1   0       110   275    0        0      118      1      1.0   
275   52    1   0       125   212    0        1      168      0      1.0   
276   58    1   0       146   218    0        1      105      0      2.0   
277   57    1   1       124   261    0        1      141      0      0.3   
278   58    0   1       136   319    1        0      152      0      0.0   
279   61    1   0       138   166    0        0      125      1      3.6   
280   42    1   0       136   315    0        1      125      1      1.8   
281   52    1   0       128   204    1        1      156      1      1.0   
282   59    1   2       126   218    1        1      134      0      2.2   
283   40    1   0       152   223    0        1      181      0      0.0   
284   61    1   0       140   207    0        0      138      1      1.9   
285   46    1   0       140   311    0        1      120      1      1.8   
286   59    1   3       134   204    0        1      162      0      0.8   
287   57    1   1       154   232    0        0      164      0      0.0   
288   57    1   0       110   335    0        1      143      1      3.0   
289   55    0   0       128   205    0        2      130      1      2.0   
290   61    1   0       148   203    0        1      161      0      0.0   
291   58    1   0       114   318    0        2      140      0      4.4   
292   58    0   0       170   225    1        0      146      1      2.8   
293   67    1   2       152   212    0        0      